# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from off_board/camera.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class camera(genpy.Message):
  _md5sum = "db349a97975dc8574cf482cb05513bb9"
  _type = "off_board/camera"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool find_obs_flag
float32 dis
float32 pos_left
float32 pos_right
float32 x_pos
float32 y_pos"""
  __slots__ = ['find_obs_flag','dis','pos_left','pos_right','x_pos','y_pos']
  _slot_types = ['bool','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       find_obs_flag,dis,pos_left,pos_right,x_pos,y_pos

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(camera, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.find_obs_flag is None:
        self.find_obs_flag = False
      if self.dis is None:
        self.dis = 0.
      if self.pos_left is None:
        self.pos_left = 0.
      if self.pos_right is None:
        self.pos_right = 0.
      if self.x_pos is None:
        self.x_pos = 0.
      if self.y_pos is None:
        self.y_pos = 0.
    else:
      self.find_obs_flag = False
      self.dis = 0.
      self.pos_left = 0.
      self.pos_right = 0.
      self.x_pos = 0.
      self.y_pos = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B5f().pack(_x.find_obs_flag, _x.dis, _x.pos_left, _x.pos_right, _x.x_pos, _x.y_pos))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.find_obs_flag, _x.dis, _x.pos_left, _x.pos_right, _x.x_pos, _x.y_pos,) = _get_struct_B5f().unpack(str[start:end])
      self.find_obs_flag = bool(self.find_obs_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B5f().pack(_x.find_obs_flag, _x.dis, _x.pos_left, _x.pos_right, _x.x_pos, _x.y_pos))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.find_obs_flag, _x.dis, _x.pos_left, _x.pos_right, _x.x_pos, _x.y_pos,) = _get_struct_B5f().unpack(str[start:end])
      self.find_obs_flag = bool(self.find_obs_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B5f = None
def _get_struct_B5f():
    global _struct_B5f
    if _struct_B5f is None:
        _struct_B5f = struct.Struct("<B5f")
    return _struct_B5f
