# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from motion_planning/camera_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class camera_msg(genpy.Message):
  _md5sum = "114e47e9e532df1ce24754afff3794bc"
  _type = "motion_planning/camera_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool find_box_flag
float64 x_center_dis
float64 y_center_dis
float64 box_hight
"""
  __slots__ = ['find_box_flag','x_center_dis','y_center_dis','box_hight']
  _slot_types = ['bool','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       find_box_flag,x_center_dis,y_center_dis,box_hight

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(camera_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.find_box_flag is None:
        self.find_box_flag = False
      if self.x_center_dis is None:
        self.x_center_dis = 0.
      if self.y_center_dis is None:
        self.y_center_dis = 0.
      if self.box_hight is None:
        self.box_hight = 0.
    else:
      self.find_box_flag = False
      self.x_center_dis = 0.
      self.y_center_dis = 0.
      self.box_hight = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B3d().pack(_x.find_box_flag, _x.x_center_dis, _x.y_center_dis, _x.box_hight))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.find_box_flag, _x.x_center_dis, _x.y_center_dis, _x.box_hight,) = _get_struct_B3d().unpack(str[start:end])
      self.find_box_flag = bool(self.find_box_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B3d().pack(_x.find_box_flag, _x.x_center_dis, _x.y_center_dis, _x.box_hight))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.find_box_flag, _x.x_center_dis, _x.y_center_dis, _x.box_hight,) = _get_struct_B3d().unpack(str[start:end])
      self.find_box_flag = bool(self.find_box_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B3d = None
def _get_struct_B3d():
    global _struct_B3d
    if _struct_B3d is None:
        _struct_B3d = struct.Struct("<B3d")
    return _struct_B3d
